
import React from 'react';
import { Rune, Spread } from './types';

export const ELDER_FUTHARK: Rune[] = [
  { name: 'Fehu', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2 L12 30 M2 12 L12 12 M2 7 L12 7"/></svg>, keywords: ['Wealth', 'Abundance', 'Success'], meaning: 'Represents material wealth, prosperity, and financial strength. It signifies new beginnings and earned income.', reversedKeywords: ['Loss', 'Greed', 'Burnout'], reversedMeaning: 'Loss of personal property or esteem. Greed, burnout, atrophy, or discord.' },
  { name: 'Uruz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M6 30V6 M18 30V14C18 8 6 8 6 14"/></svg>, keywords: ['Strength', 'Endurance', 'Health'], meaning: 'Symbolizes raw power, vitality, and untamed potential. It represents physical and mental strength, and perseverance.', reversedKeywords: ['Weakness', 'Obsession', 'Sickness'], reversedMeaning: 'Weakness, obsession, misdirected force, or domination by others. Sickness or inconsistency.' },
  { name: 'Thurisaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2V30 M12 13L20 16L12 19Z"/></svg>, keywords: ['Giant', 'Force', 'Conflict'], meaning: 'Represents a powerful, chaotic force. It can signify conflict, but also protection and the will to resist unwanted conflicts.', reversedKeywords: ['Danger', 'Defenselessness', 'Betrayal'], reversedMeaning: 'Danger, defenselessness, compulsion, betrayal. Malice, hatred, torment, or lies.' },
  { name: 'Ansuz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M10 2 L10 30 M10 6 L20 10 M10 14 L20 18"/></svg>, keywords: ['Communication', 'Wisdom', 'Truth'], meaning: 'The rune of the divine breath, representing communication, inspiration, and wisdom. It signifies the importance of words and messages.', reversedKeywords: ['Misunderstanding', 'Delusion', 'Manipulation'], reversedMeaning: 'Misunderstanding, delusion, or manipulation by others. Vanity and boredom.' },
  { name: 'Raidho', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M4 4 L4 28 M4 4 L14 4 L22 16 M4 28 L14 28 L22 16"/></svg>, keywords: ['Journey', 'Movement', 'Progress'], meaning: 'Symbolizes a journey, both physical and spiritual. It represents movement, change, and taking the right path.', reversedKeywords: ['Crisis', 'Rigidity', 'Disruption'], reversedMeaning: 'Crisis, rigidity, stasis, injustice, or irrationality. Disruption or delusion.' },
  { name: 'Kenaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M16 8 L6 16 L16 24"/></svg>, keywords: ['Torch', 'Knowledge', 'Creativity'], meaning: 'The torch of knowledge and creativity. It represents illumination, inspiration, and the revealing of hidden things.', reversedKeywords: ['Disease', 'Instability', 'Exposure'], reversedMeaning: 'Disease, breakup, instability, or lack of creativity. Loss of illusion and false hope.' },
  { name: 'Gebo', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M2 2 L22 30 M22 2 L2 30"/></svg>, keywords: ['Gift', 'Partnership', 'Generosity'], meaning: 'Represents gifts, both given and received. It symbolizes partnership, generosity, and the balance of exchange.', reversedKeywords: ['Gift', 'Partnership', 'Generosity'], reversedMeaning: 'Represents gifts, both given and received. It symbolizes partnership, generosity, and the balance of exchange.' },
  { name: 'Wunjo', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2 L12 30 M2 16 L12 16 M2 16 L12 8 Z"/></svg>, keywords: ['Joy', 'Harmony', 'Success'], meaning: 'The rune of joy, harmony, and fellowship. It signifies happiness, success in endeavors, and emotional satisfaction.', reversedKeywords: ['Sorrow', 'Strife', 'Alienation'], reversedMeaning: 'Sorrow, strife, alienation. Delirium, intoxication, or impractical enthusiasm.' },
  { name: 'Hagalaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M4 2 L4 30 M20 2 L20 30 M4 16 L20 16"/></svg>, keywords: ['Hail', 'Disruption', 'Change'], meaning: 'Represents hail, a sudden and destructive force of nature. It signifies unavoidable disruption, radical change, and karmic lessons.', reversedKeywords: ['Hail', 'Disruption', 'Change'], reversedMeaning: 'Represents hail, a sudden and destructive force of nature. It signifies unavoidable disruption, radical change, and karmic lessons.' },
  { name: 'Nauthiz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2V30 M6 10L18 22"/></svg>, keywords: ['Need', 'Constraint', 'Patience'], meaning: 'Symbolizes need, restriction, and constraint. It teaches patience, resilience, and the value of overcoming hardship.', reversedKeywords: ['Distress', 'Toil', 'Deprivation'], reversedMeaning: 'Constraint of freedom, distress, toil. Want, deprivation, anguish, or misery.' },
  { name: 'Isa', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2 L12 30"/></svg>, keywords: ['Ice', 'Stasis', 'Challenge'], meaning: 'Represents ice, a state of stillness and stasis. It signifies challenges, blockages, and a time for introspection and waiting.', reversedKeywords: ['Ice', 'Stasis', 'Challenge'], reversedMeaning: 'Represents ice, a state of stillness and stasis. It signifies challenges, blockages, and a time for introspection and waiting.' },
  { name: 'Jera', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M2 8 L12 16 L2 24 M22 8 L12 16 L22 24"/></svg>, keywords: ['Harvest', 'Cycle', 'Reward'], meaning: 'Symbolizes the harvest and the cycle of seasons. It represents the rewards of hard work, fruition of plans, and the natural order.', reversedKeywords: ['Harvest', 'Cycle', 'Reward'], reversedMeaning: 'Symbolizes the harvest and the cycle of seasons. It represents the rewards of hard work, fruition of plans, and the natural order.' },
  { name: 'Eihwaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2V30 M12 30L6 24 M12 2L18 8"/></svg>, keywords: ['Yew Tree', 'Defense', 'Endurance'], meaning: 'Represents the yew tree, symbolizing defense, endurance, and the connection between life and death. It signifies strength in adversity.', reversedKeywords: ['Confusion', 'Destruction', 'Weakness'], reversedMeaning: 'Confusion, destruction, dissatisfaction, or weakness.' },
  { name: 'Perthro', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M8 2V30 M8 8H14C18 8 18 16 14 16H8"/></svg>, keywords: ['Mystery', 'Fate', 'Secrets'], meaning: 'A rune of mystery, fate, and hidden things. It signifies chance, secrets, and the unfolding of destiny.', reversedKeywords: ['Addiction', 'Stagnation', 'Loneliness'], reversedMeaning: 'Addiction, stagnation, loneliness, or malaise.' },
  { name: 'Algiz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M4 18L12 6L20 18 M12 6V18"/></svg>, keywords: ['Protection', 'Spirit', 'Shield'], meaning: 'Represents divine protection and a spiritual shield. It signifies defense, connection to higher consciousness, and warding off evil.', reversedKeywords: ['Hidden Danger', 'Warning', 'Taboo'], reversedMeaning: 'Hidden danger, consumption by divine forces, loss of divine link. A warning against that which repels.' },
  { name: 'Sowilo', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M8 2 L20 14 L8 14 L16 30 L4 18 L16 18 Z"/></svg>, keywords: ['Sun', 'Success', 'Vitality'], meaning: 'Symbolizes the sun, bringing success, vitality, and positive energy. It represents clarity, victory, and personal power.', reversedKeywords: ['Sun', 'Success', 'Vitality'], reversedMeaning: 'Symbolizes the sun, bringing success, vitality, and positive energy. It represents clarity, victory, and personal power.' },
  { name: 'Tiwaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2V30 M4 8L12 2L20 8"/></svg>, keywords: ['Justice', 'Honor', 'Leadership'], meaning: 'Named after the god Tyr, it represents justice, honor, and self-sacrifice. It signifies leadership, rationality, and victory in legal matters.', reversedKeywords: ['Injustice', 'Conflict', 'Failure'], reversedMeaning: 'Mental paralysis, over-analysis, over-sacrifice, injustice, or imbalance. Strife, war, and failure in competition.' },
  { name: 'Berkano', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M8 2V30 M8 2H14C18 2 18 10 14 10H8 M8 16H16C20 16 20 26 16 26H8"/></svg>, keywords: ['Birth', 'Growth', 'New Beginnings'], meaning: 'The rune of birth, growth, and new beginnings. It represents family, fertility, and the nurturing aspects of life.', reversedKeywords: ['Family Problems', 'Anxiety', 'Strife'], reversedMeaning: 'Family problems, domestic strife, or anxiety about someone close to you. Carelessness or loss of control.' },
  { name: 'Ehwaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M6 30V2L12 16L18 2V30"/></svg>, keywords: ['Horse', 'Movement', 'Partnership'], meaning: 'Represents the horse, symbolizing movement, travel, and swift change. It signifies trust, loyalty, and partnership.', reversedKeywords: ['Restlessness', 'Mistrust', 'Betrayal'], reversedMeaning: 'A craving for change, feeling held back. Restlessness, disharmony, mistrust, or betrayal.' },
  { name: 'Mannaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M4 2 L4 30 M20 2 L20 30 M4 10 L12 22 M20 10 L12 22"/></svg>, keywords: ['Humanity', 'Self', 'Community'], meaning: 'The rune of humanity, representing the self in relation to others. It signifies community, social order, and shared human experience.', reversedKeywords: ['Depression', 'Mortality', 'Self-delusion'], reversedMeaning: 'Depression, mortality, blindness, or self-delusion. Slyness, manipulation, and calculation. Expect no help from others.' },
  { name: 'Laguz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M8 2 L8 30 M18 24 L8 30"/></svg>, keywords: ['Water', 'Flow', 'Intuition'], meaning: 'Represents water, flow, and intuition. It signifies emotions, dreams, and the power of the unconscious mind.', reversedKeywords: ['Confusion', 'Fear', 'Withering'], reversedMeaning: 'A period of confusion. You may be making wrong decisions. Lack of creativity, fear, avoidance, or withering.' },
  { name: 'Ingwaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2 L22 16 L12 30 L2 16 Z"/></svg>, keywords: ['Fertility', 'Potential', 'Completion'], meaning: 'Named after the god Ing, it represents fertility and internal growth. It signifies the completion of a phase and stored potential.', reversedKeywords: ['Fertility', 'Potential', 'Completion'], reversedMeaning: 'Named after the god Ing, it represents fertility and internal growth. It signifies the completion of a phase and stored potential.' },
  { name: 'Dagaz', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M4 4L12 16L4 28 M20 4L12 16L20 28"/></svg>, keywords: ['Day', 'Awakening', 'Breakthrough'], meaning: 'Symbolizes day, awakening, and breakthrough. It represents clarity, hope, and the balance between opposites.', reversedKeywords: ['Day', 'Awakening', 'Breakthrough'], reversedMeaning: 'Symbolizes day, awakening, and breakthrough. It represents clarity, hope, and the balance between opposites.' },
  { name: 'Othala', symbol: <svg viewBox="0 0 24 32" stroke="currentColor" strokeWidth="2" fill="none"><path d="M12 2L20 10L12 18L4 10Z M8 16L4 30 M16 16L20 30"/></svg>, keywords: ['Inheritance', 'Heritage', 'Home'], meaning: 'Represents ancestral heritage, inheritance, and home. It signifies family legacy, tradition, and a sense of belonging.', reversedKeywords: ['Poverty', 'Homelessness', 'Prejudice'], reversedMeaning: 'Lack of customary order, slavery, poverty, homelessness. Bad karma, prejudice, or clannishness.' },
  { name: 'Blank Rune', symbol: <svg viewBox="0 0 24 32"></svg>, keywords: ['Unknown', 'Destiny', 'Potential'], meaning: 'The rune of the unknown, representing pure potential and destiny. It signifies that which is unknowable or not yet meant to be revealed.', reversedKeywords: ['Unknown', 'Destiny', 'Potential'], reversedMeaning: 'The rune of the unknown, representing pure potential and destiny. It signifies that which is unknowable or not yet meant to be revealed.' },
];

export const SPREADS: Spread[] = [
    { name: 'Single Rune', description: 'A quick insight into a single issue.', runeCount: 1 },
    { name: 'Three Rune Spread', description: 'Past, Present, and Future influences.', runeCount: 3 },
    { name: 'Five Rune Spread', description: 'A deeper look into your situation.', runeCount: 5 },
];
